description: msinfo manuals
theme: jekyll-theme-minimal
encoding: UTF-8
timezone: Asia/Tokyo
auto: true
server: true
stylesheet: ["/css/style.css"]
search_in_topnav: true
search_in_sidebar: false
toggle-sidebar-button: true
sidebars:
  - chapter-1
  - chapter-2
