description: msinfo manuals
theme: jekyll-theme-minimal
encoding: UTF-8
timezone: Asia/Tokyo
auto: true
server: true
stylesheet: ["/css/style.css"]
sidebar:
  - title: "Title"
    text: "Some text here."
  - title: "Another Title"
    text: "More text here."
